version: 2
updates:
  - package-ecosystem: nuget
    directory: "/dotnet"
    schedule:
      interval: daily
      time: "11:00"
    commit-message:
      prefix: "[Production]"
      prefix-development: "[Development]"
  - package-ecosystem: npm
    directory: "/api"
    schedule:
      interval: daily
      time: "11:00"
  - package-ecosystem: "github-actions"
    directory: "/api"
    schedule:
      interval: "daily"
      time: "11:00"
